export { default as IconBook } from "./book";
export { default as IconChecked } from "./checked";
export { default as IconClose } from "./close";
export { default as IconFacebook } from "./facebook";
export { default as IconInstagram } from "./instagram";
export { default as IconLinkedin } from "./linkedin";
export { default as IconLocation } from "./locationdot";
export { default as IconPhone } from "./phone";
export { default as IconWhatsapp } from "./whatsapp";
